[package]
name = "thumbkey"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.0"
thiserror = "2.0.11"
tokio = {version = "1.43.0", features = ["rt-multi-thread","macros","time","signal"]}
tokio-util = "0.7.13"
[build-dependencies]
bindgen = "0.71.0"
[features]
